# (Webscraping & Sentiment Analysis) Movie Overview from Themoviedb.org

#### Themoviedb.org is a popular website that aggregates movie overviews, reviews and ratings for movies and TV shows. It provides a comprehensive overview of the critical and audience reception of various entertainment content

### a. Key features: movie's basic information (movie id, title, release date, vote average, overview, runtime, box office earning)
### b. The collected dataset spans a period of 5 months from 1st January 2025 to 1st June 2025

# GOAL: Explore Themoviedb.org to discover the trending movie and the sentiment its movie overviews

# 1. Crawl data using API of TMDB (Themoviedb.org)

In [92]:
import requests
import pandas as pd

API_KEY = "8ebc019c041f4ba9fdc43675eb228764"
BASE_URL = "https://api.themoviedb.org/3/discover/movie"
MOVIE_URL = "https://api.themoviedb.org/3/movie/"

movies = []
page = 1
total_pages = 30 

while page <= total_pages:
    params = {
        "api_key": API_KEY,
        "language": "en-US",
        "sort_by": "popularity.desc",
        "primary_release_date.gte": "2025-01-01",
        "primary_release_date.lte": "2025-06-01",
        "page": page,
    }
    #Send request to API
    response = requests.get(BASE_URL, params=params)
    data = response.json()
    
    print(f"Page {page} - Movies found: {len(data.get('results', []))}")
    
    for movie in data.get("results", []):
        # Get information about each movie
        movie_id = movie["id"]
        movie_details = requests.get(f"{MOVIE_URL}{movie_id}", params={"api_key": API_KEY, "language": "en-US"}).json()
    
        box_office_earnings = movie_details.get("revenue", 0)  # Box office earnings 
        runtime = movie_details.get("runtime", 0)  # Runtime
        
        movies.append({
            "id": movie["id"],
            "title": movie["title"],
            "original_title": movie.get("original_title", ""),
            "release_date": movie.get("release_date", ""),
            "popularity": movie.get("popularity", 0),
            "vote_average": movie.get("vote_average", 0),
            "vote_count": movie.get("vote_count", 0),
            "overview": movie.get("overview", ""),
            "runtime": runtime,
            "box_office_earnings": box_office_earnings
        })
    
    page += 1

Page 1 - Movies found: 20
Page 2 - Movies found: 20
Page 3 - Movies found: 20
Page 4 - Movies found: 20
Page 5 - Movies found: 20
Page 6 - Movies found: 20
Page 7 - Movies found: 20
Page 8 - Movies found: 20
Page 9 - Movies found: 20
Page 10 - Movies found: 20
Page 11 - Movies found: 20
Page 12 - Movies found: 20
Page 13 - Movies found: 20
Page 14 - Movies found: 20
Page 15 - Movies found: 20
Page 16 - Movies found: 20
Page 17 - Movies found: 20
Page 18 - Movies found: 20
Page 19 - Movies found: 20
Page 20 - Movies found: 20
Page 21 - Movies found: 20
Page 22 - Movies found: 20
Page 23 - Movies found: 20
Page 24 - Movies found: 20
Page 25 - Movies found: 20
Page 26 - Movies found: 20
Page 27 - Movies found: 20
Page 28 - Movies found: 20
Page 29 - Movies found: 20
Page 30 - Movies found: 20
        id            title   original_title release_date  popularity  \
0   870028  The Accountant²  The Accountant²   2025-04-23    585.1611
1   552524    Lilo & Stitch    Lilo & Stitch   2025-05-17    457.1902
2  1315988          Mikaela          Mikaela   2025-01-31    434.0803
3  1233413          Sinners          Sinners   2025-04-16    333.1718
4  1087891      The Amateur      The Amateur   2025-04-09    454.4510

   vote_average  vote_count  \
0         7.200         670
1         7.100         605
2         6.186          43
3         7.554        1386
4         6.804         369

                                            overview  runtime  \
0  When an old acquaintance is murdered, Wolff is...      133
1  The wildly funny and touching story of a lonel...      108
2  During the eve of the 6th of January, a record...       90
3  Trying to leave their troubled lives behind, t...      138
4  After his life is turned upside down when his ...      123

   box_office_earnings
0            102116542
1            807600000
2                    0
3            357628506
4             95808586

In [94]:
df_movies = pd.DataFrame(movies)
df_movies

,id,title,original_title,release_date,popularity,vote_average,vote_count,overview,runtime,box_office_earnings
0,870028,The Accountant²,The Accountant²,2025-04-23,585.1611,7.200,670,"When an old acquaintance is murdered, Wolff is...",133,102116542
1,552524,Lilo & Stitch,Lilo & Stitch,2025-05-17,457.1902,7.100,605,The wildly funny and touching story of a lonel...,108,807600000
2,1315988,Mikaela,Mikaela,2025-01-31,434.0803,6.186,43,"During the eve of the 6th of January, a record...",90,0
3,1233413,Sinners,Sinners,2025-04-16,333.1718,7.554,1386,"Trying to leave their troubled lives behind, t...",138,357628506
4,1087891,The Amateur,The Amateur,2025-04-09,454.4510,6.804,369,After his life is turned upside down when his ...,123,95808586
...,...,...,...,...,...,...,...,...,...,...
595,1414052,Mr.Robot,미스터 로봇,2025-04-04,1.0231,5.000,2,A futuristic world where robots have become po...,90,0
596,1465026,Untold: The Fall of Favre,Untold: The Fall of Favre,2025-05-19,1.2069,5.583,12,This eye-opening documentary delves into Brett...,64,0
597,1176529,Everything About My Wife,Everything About My Wife,2025-02-26,1.0088,1.000,1,The film revolves around an unhappy married ma...,110,0
598,1414275,Diddy: Monster's Fall,Diddy: Monster's Fall,2025-01-10,1.0671,6.500,2,"Disgraced hip-hop mogul, Sean 'Diddy' Combs co...",60,0
599,1441461,Kolektor,Kolektor,2025-03-07,1.2967,0.000,0,"Jessie, a single man trying to look for love. ...",96,0

### Convert the variable "release_date" which is under the form of date into the numeric variables named "Days_since_release"

In [97]:
df_movies['release_date'] = pd.to_datetime(df_movies['release_date'])

In [99]:
reference_date = pd.to_datetime('2025-06-13')

In [101]:
df_movies['days_since_release'] = (reference_date-df_movies['release_date']).dt.days
df_movies

,id,title,original_title,release_date,popularity,vote_average,vote_count,overview,runtime,box_office_earnings,days_since_release
0,870028,The Accountant²,The Accountant²,2025-04-23,585.1611,7.200,670,"When an old acquaintance is murdered, Wolff is...",133,102116542,51.0
1,552524,Lilo & Stitch,Lilo & Stitch,2025-05-17,457.1902,7.100,605,The wildly funny and touching story of a lonel...,108,807600000,27.0
2,1315988,Mikaela,Mikaela,2025-01-31,434.0803,6.186,43,"During the eve of the 6th of January, a record...",90,0,133.0
3,1233413,Sinners,Sinners,2025-04-16,333.1718,7.554,1386,"Trying to leave their troubled lives behind, t...",138,357628506,58.0
4,1087891,The Amateur,The Amateur,2025-04-09,454.4510,6.804,369,After his life is turned upside down when his ...,123,95808586,65.0
...,...,...,...,...,...,...,...,...,...,...,...
595,1414052,Mr.Robot,미스터 로봇,2025-04-04,1.0231,5.000,2,A futuristic world where robots have become po...,90,0,70.0
596,1465026,Untold: The Fall of Favre,Untold: The Fall of Favre,2025-05-19,1.2069,5.583,12,This eye-opening documentary delves into Brett...,64,0,25.0
597,1176529,Everything About My Wife,Everything About My Wife,2025-02-26,1.0088,1.000,1,The film revolves around an unhappy married ma...,110,0,107.0
598,1414275,Diddy: Monster's Fall,Diddy: Monster's Fall,2025-01-10,1.0671,6.500,2,"Disgraced hip-hop mogul, Sean 'Diddy' Combs co...",60,0,154.0
599,1441461,Kolektor,Kolektor,2025-03-07,1.2967,0.000,0,"Jessie, a single man trying to look for love. ...",96,0,98.0

# 2. Sentiment Analysis of Film Overview

In [103]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer

In [105]:
import nltk
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /Users/harley.le/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

True

In [107]:
vader = SentimentIntensityAnalyzer()

In [109]:
df_movies["overview"]

0      When an old acquaintance is murdered, Wolff is...
1      The wildly funny and touching story of a lonel...
2      During the eve of the 6th of January, a record...
3      Trying to leave their troubled lives behind, t...
4      After his life is turned upside down when his ...
                             ...
595    A futuristic world where robots have become po...
596    This eye-opening documentary delves into Brett...
597    The film revolves around an unhappy married ma...
598    Disgraced hip-hop mogul, Sean 'Diddy' Combs co...
599    Jessie, a single man trying to look for love. ...
Name: overview, Length: 600, dtype: object

In [111]:
overview_list = df_movies["overview"].tolist()

In [113]:
overview_list

['When an old acquaintance is murdered, Wolff is compelled to solve the case. Realizing more extreme measures are necessary, Wolff recruits his estranged and highly lethal brother, Brax, to help. In partnership with Marybeth Medina, they uncover a deadly conspiracy, becoming targets of a ruthless network of killers who will stop at nothing to keep their secrets buried.',
 'The wildly funny and touching story of a lonely Hawaiian girl and the fugitive alien who helps to mend her broken family.',
 'During the eve of the 6th of January, a record-breaking snowstorm sweeps across Spain. In the midst of its chaos, a group of robbers seizes the opportunity to hijack an armoured van. A few meters away is Leo, a finished policeman who has nothing to lose. With the unexpected aid of a young woman, he will try to stop the band from running away with their loot.',
 'Trying to leave their troubled lives behind, twin brothers return to their hometown to start again, only to discover that an even greater evil is waiting to welcome them back.',
 'After his life is turned upside down when his wife is killed in a London terrorist attack, a brilliant but introverted CIA decoder takes matters into his own hands when his supervisors refuse to take action.',
 "Four misfits find themselves struggling with ordinary problems when they are suddenly pulled through a mysterious portal into the Overworld: a bizarre, cubic wonderland that thrives on imagination. To get back home, they'll have to master this world while embarking on a magical quest with an unexpected, expert crafter, Steve.",
 'Plagued by a violent recurring nightmare, college student Stefanie heads home to track down the one person who might be able to break the cycle and save her family from the grisly demise that inevitably awaits them all.',
 "Kyrah and Isaac were once the leaders of a multinational special forces group called Shadow Force. They broke the rules by falling in love, and in order to protect their son, they go underground. With a large bounty on their heads, and the vengeful Shadow Force hot on their trail, one family's fight becomes all-out war.",
 "Levon Cade left behind a decorated military career in the black ops to live a simple life working construction. But when his boss's daughter, who is like family to him, is taken by human traffickers, his search to bring her home uncovers a world of corruption far greater than he ever could have imagined.",
 'In this high-octane battle of wits and wills, ingenious con artist Rehan devises a diamond heist while trying to outsmart Rajan, his sadistic adversary.',
 'Quinn and her father have just moved to the quiet town of Kettle Springs hoping for a fresh start. Instead, she discovers a fractured community that has fallen on hard times after the treasured Baypen Corn Syrup Factory burned down. As the locals bicker amongst themselves and tensions boil over, a sinister, grinning figure emerges from the cornfields to cleanse the town of its burdens, one bloody victim at a time.',
 'In a fairy-tale kingdom where beauty is a brutal business, Elvira battles to compete with her incredibly beautiful stepsister, and she will go to any length to catch the prince’s eye.',
 "Ethan Hunt and team continue their search for the terrifying AI known as the Entity — which has infiltrated intelligence networks all over the globe — with the world's governments and a mysterious ghost from Hunt's past on their trail. Joined by new allies and armed with the means to shut the Entity down for good, Hunt is in a race against time to prevent the world as we know it from changing forever.",
 'A tragic accident pushes the powerful Sikandar to protect the less fortunate by standing up to corruption and greed — using any means necessary.',
 'A platoon of Navy SEALs embarks on a dangerous mission in Ramadi, Iraq, with the chaos and brotherhood of war retold through their memories of the event.',
 'A rag-tag team of divers attempting to salvage a sunken car from a river are thwarted by a highly aggressive bull shark.',
 "Following the benevolent King's disappearance, the Evil Queen dominated the once fair land with a cruel streak. Princess Snow White flees the castle when the Queen, in her jealousy over Snow White's inner beauty, tries to kill her. Deep into the dark woods, she stumbles upon seven magical dwarves and a young bandit named Jonathan. Together, they strive to survive the Queen's relentless pursuit and aspire to take back the kingdom.",
 'Sonu Model, a renowned beautician from the old city, is forced to disguise himself as Laila, leading to a series of comedic, romantic, and action-packed events. Chaos ensues in this hilarious laugh riot',
 'A queen sends the powerful and feared sorceress Gray Alys to the ghostly wilderness of the Lost Lands in search of a magical power, where she and her guide, the drifter Boyce, must outwit and outfight both man and demon.',
 'One year after her sister Melanie mysteriously disappeared, Clover and her friends head into the remote valley where she vanished in search of answers. Exploring an abandoned visitor center, they find themselves stalked by a masked killer and horrifically murdered one by one...only to wake up and find themselves back at the beginning of the same evening.',
 'After finding themselves ensnared in a death trap, seven disillusioned castoffs must embark on a dangerous mission that will force them to confront the darkest corners of their pasts.',
 'After meeting with newly elected U.S. President Thaddeus Ross, Sam finds himself in the middle of an international incident. He must discover the reason behind a nefarious global plot before the true mastermind has the entire world seeing red.',
 "After a family tragedy, kung fu prodigy Li Fong is uprooted from his home in Beijing and forced to move to New York City with his mother. When a new friend needs his help, Li enters a karate competition – but his skills alone aren't enough. Li's kung fu teacher Mr. Han enlists original Karate Kid Daniel LaRusso for help, and Li learns a new way to fight, merging their two styles into one for the ultimate martial arts showdown.",
 'When her son vanishes inside a US consulate, ex-special forces soldier Sara does everything in her power to find him — and uncovers a dark conspiracy.',
 "An ex-special forces operative seeks revenge against a cult leader who has corrupted his former comrades, the Shinjas. This leader, known as The Bokushi, promises veterans a purpose and protection, but is revealed to be a destructive influence. The ex-soldier, Nash Cavanaugh, joins forces with military operative Emmanuel Ashburn to infiltrate the Bokushi's fortress and expose his reign of terror",
 'In a remote village on the island of Carpathia, a shy farm girl named Yuri is raised to fear an elusive animal species known as ochi. But when Yuri discovers a wounded baby ochi has been left behind, she escapes on a quest to bring him home.',
 'A courageous and athletic teenager, Kayara dreams that she is destined to be the first female to break into the league of Chasquis - the official messengers of the Incan empire. As she learns what it takes to be a Chasqui along with its challenges, she tackles every mission she gets and discovers the ancient stories of her land and her people.',
 'Audrey Avila, Denise Esteban and Dani Yoshida star as sultry Belyas. A housewife who is tired of her controlling husband takes a different turn when two young prostitutes rent their apartment. As she befriends the two, she begins to admire the sexual freedom they have.',
 "When a man is found dead, the investigation shatters his widow's perfect facade and exposes a hidden double life in this thriller based on real events.",
 'Car genius Lino returns to conclude his vendetta against Areski and the corrupt commander who ruined their lives in this turbo-charged trilogy finale.',
 'Alvaro, an optimistic young man falls in love with Carla, a girl who is in a mental clinic. In trying to help her, he learns that mental illness requires more than just a positive attitude to overcome.',
 "Who will be voted queen at Shadyside High's 1988 prom? For underdog Lori, competition is cutthroat even before someone starts killing off the candidates.",
 "Wall Street stockbroker Rosario Fuentes returns to her grandmother's apartment after her sudden death. While sorting through her belongings, Rosario discovers a hidden chamber that's filled with occult artifacts tied to dark generational rituals. As supernatural occurrences begin to plague her, she must confront her family's buried secrets and face the truth about the sacrifices and choices they made.",
 "When a drug heist swerves lethally out of control, a jaded cop fights his way through a corrupt city's criminal underworld to save a politician's son.",
 'Two highly trained operatives grow close from a distance after being sent to guard opposite sides of a mysterious gorge. When an evil below emerges, they must work together to survive what lies within.',
 "A treasure-hunting mastermind assembles a team for a life-changing adventure. But to outwit and outrun threats at every turn, he'll need someone even smarter than he is: his estranged sister.",
 'Infamous outlaw Harland Rust breaks his estranged grandson Lucas out of prison, after Lucas is convicted to hang for an accidental murder. The two must outrun legendary U.S Marshal Wood Helm and bounty hunter Fenton "Preacher" Lang who are hot on their tails. Deeply buried secrets rise from the ashes and an unexpected familial bond begins to form as the mismatched duo tries to survive the merciless American Frontier.',
 'When twin brothers find a mysterious wind-up monkey, a series of outrageous deaths tear their family apart. Twenty-five years later, the monkey begins a new killing spree forcing the estranged brothers to confront the cursed toy.',
 'A father and daughter accidentally hit and kill a unicorn while en route to a weekend retreat, where his billionaire boss seeks to exploit the creature’s miraculous curative properties.',
 'When the girl of his dreams is kidnapped, everyman Nate turns his inability to feel pain into an unexpected strength in his fight to get her back.',
 'A man returns to the idyllic beach of his childhood to surf with his son. When he is humiliated by a group of locals, the man is drawn into a conflict that keeps rising and pushes him to his breaking point.',
 "A U.S. Marshal escorts a government witness to trial after he's accused of getting involved with a mob boss, only to discover that the pilot who is transporting them is also a hitman sent to assassinate the informant. After they subdue him, they're forced to fly together after discovering that there are others attempting to eliminate them.",
 'A musician plagued by insomnia is pulled into an odyssey with a stranger who begins to unravel the very core of his existence.',
 'In a career that lasted only ten years, Vincent Van Gogh painted one subject more than any other: himself. This is the story of Vincent told using eight of his most iconic self-portraits.',
 'In a small town haunted by the struggles of life and death, ghosts and humans alike embark on a desperate journey to end their torment, resorting to extreme measures to achieve their goals.',
 "18-year-old Noah moves from America to London, with her mother who's recently fallen in love with William, a wealthy British businessman. Noah meets William’s son, bad-boy Nick, and soon discovers there is an attraction between them neither can avoid. As Noah spends the summer adjusting to her new life, her devastating past will catch up with her while falling in love for the first time.",
 'When a man proposes marriage to his girlfriend, she wants to find out first if they are ready for a lifetime commitment. She meets her friend and her husband that will open up desires they are not aware of for a long time.',
 'Set in 1301 at the end of Medieval times, our most famous star-crossed lovers turn the tides on the history Shakespeare based his own story on, as they reveal the truth to the very future of the Empire. But the biggest twist in this most beloved of tales, is leaving the poetry of Iambic Pentameter in the past, for the original pop music that rockets these ever-present themes right to the heart of our characters in the most surprising, and perhaps most powerful way that has ever been seen, or heard, before... The greatest love story of all time, set to the greatest music of our time.',
 '2021. After spending a year in confinement, a group of high school students and their two teachers begin an end-of-year trip to Mallorca. This great plan is the last opportunity they have to all be together, make up for lost time, be able to have fun like they have never had before and say goodbye to this crazy stage of their lives. However, a new coronavirus outbreak disrupts all their plans and forces them to stay locked in their hotel rooms. More than 50 students, 2 teachers, a hotel and many, many minibars... What could go wrong?',
 'A group of billionaire friends get together against the backdrop of a rolling international crisis.',
 "During a wedding in a riad on the edge of the Moroccan desert, Paul meets Louna, the bride's sister and witness. Following a paranormal event, they both find themselves trapped in the same space-time, forced to live the same day over and over again. And so begins a love story set against the backdrop of a time loop and a never-ending marriage…",
 'When a devil-worshipping criminal network plunges Seoul into chaos, the police turn to Holy Night—a trio of supernatural demon hunters—to restore order and defeat the rising evil.',
 'Jéssica (Thati Lopes) is a simple young woman, dedicated to her job at an antique shop in Rio de Janeiro, but she feels her life lacks purpose. Everything changes when she finds a mysterious locket identical to an item she inherited from her late mother. Driven by the desire to understand the connection between the locket and her family history, Jéssica teams up with Gabriel (Rodrigo Simas), a distant relative who appears unexpectedly.',
 "A woman's peaceful mountain getaway takes a bizarre turn when her boyfriend disappears, and a random naked man shows up claiming to be him.",
 'Unlikely hero Mickey Barnes finds himself in the extraordinary circumstance of working for an employer who demands the ultimate commitment to the job… to die, for a living.',
 'When an astronaut leaves Earth for Mars, the vast infinite space divides star-crossed lovers in this animated romance that crosses the cosmos.',
 'When panic erupts on a Tokyo-bound bullet train that will explode if it slows below 100 kph, authorities race against time to save everyone on board.',
 'Wealthy businessman Zsa-zsa Korda appoints his only daughter, a nun, as sole heir to his estate. As Korda embarks on a new enterprise, they soon become the target of scheming tycoons, foreign terrorists, and determined assassins.',
 'Witness the never-before-seen footage and true story behind the John Wick phenomenon – from independent film to billion-dollar franchise.',
 'During a weekend getaway at a secluded lakeside estate, a group of friends finds themselves entangled in a web of secrets, deception, and advanced technology. As tensions rise and loyalties are tested, they uncover unsettling truths about themselves and the world around them.',
 'Following the Tribulation, although the souls of Ne Zha and Ao Bing were preserved, their physical bodies will soon be destroyed. Tai Yi Zhen Ren plans to use the Seven Colored Lotus to reshape their physical forms, but encounters numerous difficulties. What will become of Ne Zha and Ao Bing?',
 "In the aftermath of her husband's death, widow Ramona's struggle to raise her two kids is hindered by the arrival of a mysterious woman with supernatural abilities.",
 'After the G20 Summit is overtaken by terrorists, President Danielle Sutton must bring all her statecraft and military experience to defend her family and her fellow leaders.',
 'Violence and mayhem ensue after a smuggler escapes with a rare Ife bronze head into a gritty western Nigerian town.',
 'A newly appointed small-town sheriff and his begrudging deputy get tangled up in a web of lies and corruption involving shady businessmen and the cartel while investigating the murder of a mysterious woman.',
 'Put-upon lawman John Dorsey is on the verge of losing his wife and his job as sheriff, so he posses up with bullish U.S. Marshall Butch Hayden to hold outlaw Emily Rusk hostage. A battle of wills ensues as Emily turns the posse on themselves, but as her marauding husband and his gang approach, Emily and John realize they will need each other to survive.',
 'Violet, a widowed mother on her first date in years, arrives at an upscale restaurant where she is relieved that her date, Henry, is more charming and handsome than she expected. But their chemistry begins to curdle as Violet begins being irritated and then terrorized by a series of anonymous drops to her phone.',
 'David Attenborough takes viewers on a breathtaking journey showing there is nowhere more vital for our survival, more full of life, wonder, or surprise, than the\u202focean. Through spectacular sequences featuring coral reefs, kelp forests and the open ocean, Attenborough shares why a healthy ocean keeps the entire planet stable and flourishing.',
 'When a hostage rescue mission creates a new enemy, Capt. Guerrero and his elite soldiers must face an ambush by a criminal group.',
 'A sultry woman who charms the hearts of men in a remote province. Dolores, a devoted wife to her paraplegic husband, falls for a young mountaineer. What begins as a reckless escape turns into an affair drenched in passion and secrecy.',
 'The Batman family has returned to the present to discover that Japan has disappeared, and a giant island - Hinomoto - is now in the sky over Gotham City.  At the top sit the Yakuza, a group of superpowered individuals who reign without honor or humanity and look suspiciously like the Justice League. Now, it’s up to Batman and his allies to save Gotham!',
 'Framed for his family\'s murder and left for dead, an ex-hitman will stop at nothing to exact revenge on the masked "demons" who have taken over his city.',
 "When a group of radical activists take over an energy company's annual gala, seizing 300 hostages, an ex-soldier turned window cleaner suspended 50 storeys up on the outside of the building must save those trapped inside, including her younger brother.",
 "By day, they're invisible—valets, hostesses, and bartenders at a luxury hotel. By night, they're the Carjackers, a crew of skilled drivers who track and rob wealthy clients on the road. As they plan their ultimate heist, the hotel director hires a ruthless hitman, to stop them at all costs. With danger closing in, can Nora, Zoe, Steve, and Prestance pull off their biggest score yet?",
 'When a faithful police dog and his human police officer owner are injured together on the job, a harebrained but life-saving surgery fuses the two of them together and Dog Man is born. Dog Man is sworn to protect and serve—and fetch, sit and roll over. As Dog Man embraces his new identity and strives to impress his Chief, he must stop the pretty evil plots of feline supervillain Petey the Cat.',
 'War stories about family, ethics and honor include the true story of two U.S. Marines who in a span of six seconds, must stand their ground to stop a suicide truck bomb, a Navy Corpsman who attempts to hold on to his humanity, and a WW2 soldier who gets separated from his squad and is forced to re-evaluate his code.',
 'A dedicated family man becomes obsessed with saving the lives of the car accident victims on the sharp corner in front of his house – an obsession that could cost him everything.',

In [115]:
overview_list[0]

'When an old acquaintance is murdered, Wolff is compelled to solve the case. Realizing more extreme measures are necessary, Wolff recruits his estranged and highly lethal brother, Brax, to help. In partnership with Marybeth Medina, they uncover a deadly conspiracy, becoming targets of a ruthless network of killers who will stop at nothing to keep their secrets buried.'

In [117]:
vader.polarity_scores(overview_list[0])

{'neg': 0.207, 'neu': 0.71, 'pos': 0.083, 'compound': -0.891}

In [119]:
vader.polarity_scores(overview_list[0])["compound"]

-0.891

In [121]:
sentiments = [vader.polarity_scores(o)["compound"] for o in overview_list]

In [123]:
sentiments

[-0.891,
 -0.0258,
 -0.2124,
 -0.4767,
 -0.7845,
 -0.7783,
 -0.1027,
 -0.1027,
 0.7579,
 -0.25,
 -0.7003,
 0.3167,
 0.0258,
 -0.2006,
 -0.8934,
 -0.2484,
 -0.7845,
 0.2558,
 -0.4019,
 -0.9371,
 -0.9442,
 0.4215,
 -0.8898,
 -0.5267,
 -0.9246,
 -0.2144,
 0.7506,
 0.6597,
 -0.1531,
 -0.4767,
 0.885,
 -0.6597,
 -0.5106,
 -0.6705,
 -0.802,
 0.2382,
 -0.8519,
 -0.8442,
 -0.7717,
 -0.4019,
 -0.5719,
 -0.6369,
 0.0,
 0.0,
 -0.8957,
 0.812,
 0.8074,
 0.9902,
 0.6757,
 -0.25,
 -0.2315,
 -0.9231,
 0.6757,
 -0.128,
 0.3182,
 0.7906,
 -0.0258,
 -0.0516,
 0.4215,
 0.6369,
 -0.5994,
 -0.6369,
 -0.6249,
 -0.7717,
 -0.8176,
 -0.3818,
 -0.7976,
 0.844,
 -0.3612,
 0.765,
 0.6077,
 -0.8564,
 -0.128,
 -0.7717,
 0.4118,
 -0.8957,
 -0.6705,
 -0.5574,
 0.3182,
 0.4767,
 -0.2023,
 0.1779,
 -0.631,
 -0.8225,
 0.0516,
 0.8779,
 0.3818,
 -0.4215,
 -0.5574,
 0.8977,
 -0.8807,
 0.6058,
 -0.296,
 0.6075,
 0.953,
 0.2558,
 -0.0772,
 -0.4767,
 -0.7469,
 0.0,
 0.9674,
 0.5106,
 -0.4767,
 0.0772,
 -0.7146,
 0.2023,
 0.5574,
 -0.3612,
 -0.7301,
 0.3818,
 0.128,
 -0.5719,
 -0.765,
 0.296,
 -0.9042,
 -0.8568,
 0.128,
 0.6467,
 -0.8911,
 -0.875,
 0.4215,
 -0.8885,
 -0.5106,
 -0.4854,
 -0.4404,
 0.7964,
 0.6369,
 0.6369,
 -0.1531,
 -0.899,
 -0.7269,
 0.9169,
 -0.6705,
 0.765,
 0.85,
 -0.7543,
 -0.8934,
 -0.9217,
 0.6597,
 -0.714,
 0.5859,
 0.3612,
 0.4404,
 0.0,
 -0.8347,
 -0.6124,
 0.4019,
 0.3612,
 0.7783,
 -0.0516,
 0.9042,
 0.8271,
 0.7579,
 0.7783,
 -0.9153,
 -0.8885,
 0.8625,
 -0.5574,
 -0.5719,
 0.2263,
 -0.0772,
 -0.7783,
 -0.34,
 0.7964,
 0.5859,
 0.0,
 0.7003,
 -0.5719,
 -0.8074,
 -0.3071,
 0.5267,
 0.8271,
 -0.7579,
 -0.3182,
 0.9623,
 -0.2263,
 -0.8689,
 0.4019,
 0.3182,
 -0.7906,
 -0.1779,
 0.3182,
 0.4574,
 -0.5267,
 -0.3612,
 -0.634,
 -0.2263,
 0.7421,
 -0.5423,
 0.4767,
 -0.7269,
 -0.6908,
 -0.2023,
 0.1027,
 -0.5423,
 -0.6486,
 0.4404,
 -0.8481,
 -0.7906,
 -0.8316,
 0.3182,
 -0.5859,
 -0.802,
 -0.7003,
 -0.9455,
 0.2957,
 0.0,
 0.8979,
 -0.1027,
 0.6486,
 -0.6908,
 0.6107,
 -0.7003,
 -0.1655,
 0.8074,
 0.0,
 -0.5106,
 0.128,
 -0.8555,
 -0.25,
 0.624,
 0.128,
 -0.9136,
 -0.0,
 -0.8442,
 0.128,
 0.3291,
 0.0516,
 -0.7717,
 -0.9857,
 -0.9413,
 0.8834,
 0.1027,
 -0.5023,
 0.2732,
 0.807,
 0.25,
 -0.9246,
 -0.8176,
 0.3182,
 0.4939,
 0.9226,
 -0.8519,
 -0.5267,
 0.8922,
 -0.9274,
 0.967,
 0.3818,
 0.1779,
 -0.4497,
 -0.2732,
 0.9761,
 0.2023,
 0.8225,
 -0.0516,
 -0.4767,
 -0.8908,
 0.0,
 0.9403,
 0.3182,
 0.9118,
 0.6249,
 0.6705,
 0.6782,
 -0.9089,
 0.802,
 0.1027,
 0.6369,
 0.0516,
 -0.6597,
 -0.5423,
 -0.5719,
 0.0,
 0.9169,
 -0.6369,
 -0.0258,
 0.1154,
 -0.1531,
 0.3818,
 -0.5994,
 0.5423,
 -0.765,
 0.8316,
 0.6369,
 -0.5994,
 -0.9217,
 0.296,
 0.956,
 -0.8442,
 -0.2023,
 0.6908,
 -0.7717,
 0.8479,
 -0.4404,
 0.6249,
 -0.8481,
 -0.4588,
 0.0,
 -0.8885,
 0.6428,
 0.6597,
 0.5267,
 0.128,
 -0.2023,
 -0.9246,
 0.8442,
 -0.128,
 -0.8689,
 -0.296,
 0.1779,
 -0.4767,
 0.2484,
 0.0,
 -0.6249,
 0.4939,
 -0.9217,
 0.2023,
 0.0,
 -0.431,
 -0.6486,
 0.3612,
 0.5423,
 -0.765,
 0.5994,
 0.1027,
 -0.34,
 -0.8442,
 0.8176,
 -0.5994,
 -0.8037,
 0.0,
 0.7089,
 -0.2144,
 -0.6901,
 -0.836,
 -0.7579,
 -0.836,
 0.9652,
 0.1531,
 0.5106,
 0.0,
 0.8126,
 -0.128,
 -0.7906,
 -0.9412,
 -0.8885,
 0.4939,
 0.7615,
 0.8176,
 -0.8625,
 0.4939,
 -0.6705,
 0.8176,
 -0.1406,
 0.765,
 0.1764,
 0.3818,
 0.4588,
 0.8074,
 -0.9295,
 -0.4939,
 0.4019,
 -0.4939,
 0.0,
 -0.9042,
 0.5267,
 -0.4767,
 -0.3818,
 -0.4404,
 -0.9253,
 0.8074,
 -0.8591,
 -0.9432,
 0.926,
 0.0,
 -0.6369,
 -0.5859,
 0.9217,
 0.8519,
 0.6908,
 -0.3818,
 -0.5423,
 0.7425,
 0.0258,
 -0.81,
 -0.7783,
 0.0258,
 -0.8834,
 0.4215,
 0.0,
 -0.9062,
 0.9844,
 0.9118,
 0.0,
 0.9186,
 0.5994,
 0.8573,
 0.7717,
 0.9493,
 0.9409,
 -0.6486,
 0.5859,
 -0.5106,
 -0.6808,
 -0.7964,
 -0.2732,
 -0.6705,
 0.5729,
 0.4391,
 -0.8294,
 -0.8126,
 0.8555,
 0.1401,
 -0.9001,
 0.4404,
 -0.4404,
 0.34,
 0.5423,
 -0.7351,
 0.946,
 0.6808,
 0.2732,
 -0.8482,
 0.9377,
 0.5994,
 0.4404,
 0.7845,
 -0.7964,
 0.0,
 0.4588,
 0.1779,
 -0.936,
 -0.1027,
 -0.4019,
 0.25,
 -0.25,
 -0.2023,
 -0.8126,
 0.0,
 -0.8225,
 0.296,
 -0.8225,
 0.0,
 -0.8591,
 0.4404,
 -0.9844,
 0.8201,
 0.0,
 -0.4404,
 0.8902,
 -0.6808,
 -0.7184,
 -0.9382,
 0.9796,
 -0.9136,
 -0.7096,
 -0.0258,
 -0.824,
 0.875,
 -0.8807,
 -0.8402,
 -0.4767,
 -0.5719,
 0.8979,
 -0.5423,
 0.5719,
 -0.6022,
 -0.5267,
 -0.6249,
 -0.6124,
 0.0258,
 0.6486,
 -0.8643,
 -0.5267,
 -0.0258,
 -0.3182,
 0.9702,
 -0.9601,
 0.3818,
 -0.8074,
 0.9728,
 0.9134,
 -0.8176,
 0.0,
 -0.223,
 -0.0194,
 -0.9735,
 0.4588,
 -0.9022,
 0.5562,
 0.69,
 -0.8807,
 -0.5267,
 -0.1531,
 -0.91,
 0.0,
 0.3612,
 0.7351,
 -0.7184,
 0.5423,
 0.9042,
 0.0,
 0.9118,
 -0.6597,
 0.7814,
 0.7351,
 -0.7964,
 0.6115,
 0.0,
 -0.9477,
 -0.4588,
 0.0,
 -0.8555,
 0.25,
 0.6486,
 0.9651,
 0.4497,
 -0.7684,
 0.0,
 -0.7269,
 -0.9601,
 0.0,
 -0.8442,
 -0.8225,
 0.8658,
 0.9215,
 0.0,
 0.0,
 -0.4389,
 -0.81,
 0.0,
 0.9274,
 0.8555,
 -0.6124,
 0.8074,
 0.1785,
 -0.4569,
 0.4588,
 0.5514,
 -0.8315,
 0.0,
 0.8847,
 -0.9545,
 0.128,
 -0.4767,
 -0.5859,
 0.0,
 -0.8176,
 0.6486,
 -0.8519,
 0.7003,
 0.6059,
 0.088,
 -0.5859,
 -0.8225,
 -0.743,
 0.0,
 0.8176,
 0.0258,
 -0.5994,
 0.0,
 0.743,
 -0.6059,
 -0.7748,
 0.8895,
 0.9159,
 0.0,
 0.7964,
 0.4295,
 -0.7096,
 0.8528,
 -0.4118,
 0.8519,
 -0.4215,
 0.8442,
 0.3612,
 0.2023,
 -0.3818,
 -0.09,
 -0.4404,
 0.5719,
 -0.5423,
 -0.7287,
 -0.128,
 -0.5574,
 0.25,
 0.6369,
 0.8313,
 0.2263,
 0.875,
 -0.5719,
 -0.4939,
 0.8074,
 0.75,
 -0.5994,
 -0.9517,
 -0.6124,
 -0.0258,
 -0.91,
 -0.4019]

In [125]:
df_movies["Overview_sentiment"] = sentiments

In [270]:
df_movies

,id,title,original_title,release_date,popularity,vote_average,vote_count,overview,runtime,box_office_earnings,days_since_release,Overview_sentiment
0,870028,The Accountant²,The Accountant²,2025-04-23,585.1611,7.200,670,"When an old acquaintance is murdered, Wolff is...",133,102116542,51.0,-0.8910
1,552524,Lilo & Stitch,Lilo & Stitch,2025-05-17,457.1902,7.100,605,The wildly funny and touching story of a lonel...,108,807600000,27.0,-0.0258
2,1315988,Mikaela,Mikaela,2025-01-31,434.0803,6.186,43,"During the eve of the 6th of January, a record...",90,0,133.0,-0.2124
3,1233413,Sinners,Sinners,2025-04-16,333.1718,7.554,1386,"Trying to leave their troubled lives behind, t...",138,357628506,58.0,-0.4767
4,1087891,The Amateur,The Amateur,2025-04-09,454.4510,6.804,369,After his life is turned upside down when his ...,123,95808586,65.0,-0.7845
...,...,...,...,...,...,...,...,...,...,...,...,...
595,1414052,Mr.Robot,미스터 로봇,2025-04-04,1.0231,5.000,2,A futuristic world where robots have become po...,90,0,70.0,-0.9517
596,1465026,Untold: The Fall of Favre,Untold: The Fall of Favre,2025-05-19,1.2069,5.583,12,This eye-opening documentary delves into Brett...,64,0,25.0,-0.6124
597,1176529,Everything About My Wife,Everything About My Wife,2025-02-26,1.0088,1.000,1,The film revolves around an unhappy married ma...,110,0,107.0,-0.0258
598,1414275,Diddy: Monster's Fall,Diddy: Monster's Fall,2025-01-10,1.0671,6.500,2,"Disgraced hip-hop mogul, Sean 'Diddy' Combs co...",60,0,154.0,-0.9100
599,1441461,Kolektor,Kolektor,2025-03-07,1.2967,0.000,0,"Jessie, a single man trying to look for love. ...",96,0,98.0,-0.4019

In [284]:
#The box_office_earnings variable has some missing values, which is defined as 0. Therefore, I removed these missing values to reduce the skewness of this variable when putting it into the research model
df_filtered = df_movies[df_movies['box_office_earnings'] != 0].copy()
df_filtered

,id,title,original_title,release_date,popularity,vote_average,vote_count,overview,runtime,box_office_earnings,days_since_release,Overview_sentiment
0,870028,The Accountant²,The Accountant²,2025-04-23,585.1611,7.200,670,"When an old acquaintance is murdered, Wolff is...",133,102116542,51.0,-0.8910
1,552524,Lilo & Stitch,Lilo & Stitch,2025-05-17,457.1902,7.100,605,The wildly funny and touching story of a lonel...,108,807600000,27.0,-0.0258
3,1233413,Sinners,Sinners,2025-04-16,333.1718,7.554,1386,"Trying to leave their troubled lives behind, t...",138,357628506,58.0,-0.4767
4,1087891,The Amateur,The Amateur,2025-04-09,454.4510,6.804,369,After his life is turned upside down when his ...,123,95808586,65.0,-0.7845
5,950387,A Minecraft Movie,A Minecraft Movie,2025-03-31,220.3747,6.507,1759,Four misfits find themselves struggling with o...,101,951412301,74.0,-0.7783
...,...,...,...,...,...,...,...,...,...,...,...,...
565,1376146,Hit N Fun,臨時決鬥,2025-01-28,1.4785,6.000,2,Chung Lui Society is a boxing gym founded by f...,108,1094264,136.0,0.9159
579,1390557,半⽄百两,半⽄百两,2025-01-29,1.2799,5.500,2,After successfully leading his team to crack a...,100,2245368,135.0,-0.4404
581,1276644,And the Breadwinner Is...,At ang Breadwinner Ay...,2025-01-02,3.1501,6.250,4,A mistaken identity leads to a promising oppor...,123,82649,162.0,-0.5423
583,1286264,Perayaan Mati Rasa,Perayaan Mati Rasa,2025-01-29,2.3108,7.000,7,"When they suddenly lose their parents, rival s...",125,3377757,135.0,-0.1280
587,1397679,Hot Pot Artist,火锅艺术家,2025-01-03,1.1926,4.875,8,Li Ruyi is a young man from Northeast China. H...,98,8114430,161.0,0.8313

In [288]:
df_filtered.to_excel("df_filtered.xlsx", index=False)